import type { FastifyInstance } from 'fastify';

const error = { type: 'object', properties: { ok: { type: 'boolean', example: false }, message: { type: 'string' } } };
const chatMessage = { type: 'object', required: ['role', 'content'], properties: { role: { type: 'string', enum: ['user', 'assistant'] }, content: { type: 'string' } } };
const brief = { type: 'object', properties: { summary: { type: 'string' }, system: { type: 'string' }, users: { type: 'string' }, painPoint: { type: 'string' }, dataSources: { type: 'string' }, opportunities: { type: 'array', items: { type: 'string' } }, recommendedStart: { type: 'string' }, considerations: { type: 'array', items: { type: 'string' } } } };
const lead = { type: 'object', required: ['name','email','message'], properties: { name: { type: 'string', minLength: 2 }, email: { type: 'string', format: 'email' }, company: { type: 'string' }, industry: { type: 'string' }, message: { type: 'string', minLength: 10 }, goals: { type: 'array', items: { type: 'string' } }, source: { type: 'string' }, opportunityBrief: brief } };
const request = (schema: object) => ({ required: true, content: { 'application/json': { schema } } });
const response = (description: string, schema: object) => ({ description, content: { 'application/json': { schema } } });
const bearer = [{ adminBearer: [] }];

export const openApiDocument = {
  openapi: '3.0.3',
  info: { title: 'Veyntis API', version: '1.0.0', description: 'Applied AI and systems engineering. Public discovery routes and secured lead operations. All examples are illustrative. No client data is published.' },
  servers: [{ url: 'https://veyntis-backend.vercel.app', description: 'Production API' }],
  tags: [{ name: 'System' }, { name: 'Discovery' }, { name: 'Enquiries' }, { name: 'Administration' }],
  paths: {
    '/api/health': { get: { tags: ['System'], summary: 'Basic API liveness', description: 'Checks that the API process is responding. This is not a database readiness check.', responses: { '200': response('API process responding', { type: 'object', properties: { ok: { type: 'boolean' }, service: { type: 'string' } } }) } } },
    '/api/chat': { post: { tags: ['Discovery'], summary: 'Chat with the AI discovery assistant', requestBody: request({ type: 'object', required: ['messages'], properties: { messages: { type: 'array', minItems: 1, items: chatMessage } } }), responses: { '200': response('Assistant response', { type: 'object', properties: { ok: { type: 'boolean' }, message: chatMessage } }), '400': response('Invalid conversation', error), '429': response('Rate limit', error), '502': response('Assistant unavailable', error) } } },
    '/api/opportunity-brief': { post: { tags: ['Discovery'], summary: 'Generate a focused AI opportunity brief', requestBody: request({ type: 'object', required: ['messages'], properties: { messages: { type: 'array', minItems: 1, items: chatMessage } } }), responses: { '200': response('Generated brief', { type: 'object', properties: { ok: { type: 'boolean' }, brief } }), '400': response('Invalid conversation', error), '429': response('Rate limit', error), '502': response('Generation unavailable', error) } } },
    '/api/events': { post: { tags: ['System'], summary: 'Record a first-party interaction event', requestBody: request({ type: 'object', required: ['name', 'path'], properties: { name: { type: 'string' }, path: { type: 'string' }, metadata: { type: 'object', additionalProperties: { type: 'string' } } } }), responses: { '204': { description: 'Event accepted' }, '400': response('Invalid event', error), '429': response('Rate limit', error) } } },
    '/api/leads': { post: { tags: ['Enquiries'], summary: 'Create a business enquiry', description: 'Stores an enquiry durably. Requires production database configuration; do not submit real sensitive information from the public docs.', requestBody: request(lead), responses: { '201': response('Enquiry persisted', { type: 'object', required: ['ok', 'leadId'], properties: { ok: { type: 'boolean' }, leadId: { type: 'string', format: 'uuid' } } }), '400': response('Validation error', error), '429': response('Rate limit', error), '503': response('Database not configured', error), '500': response('Persistence error', error) } } },
    '/api/admin/leads': { get: { tags: ['Administration'], summary: 'List recent enquiries', security: bearer, responses: { '200': response('Leads', { type: 'object', properties: { ok: { type: 'boolean' }, leads: { type: 'array', items: { type: 'object', additionalProperties: true } } } }), '401': response('Unauthorized', error) } } },
    '/api/admin/leads/{id}': { patch: { tags: ['Administration'], summary: 'Update enquiry status', security: bearer, parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], requestBody: request({ type: 'object', required: ['status'], properties: { status: { type: 'string', enum: ['new','contacted','qualified','closed'] } } }), responses: { '200': response('Updated lead', { type: 'object', properties: { ok: { type: 'boolean' }, lead: { type: 'object', additionalProperties: true } } }), '401': response('Unauthorized', error), '404': response('Not found', error) } } },
    '/api/admin/analytics': { get: { tags: ['Administration'], summary: 'Retrieve conversion analytics', security: bearer, responses: { '200': response('Analytics summary', { type: 'object', properties: { ok: { type: 'boolean' }, summary: { nullable: true, type: 'object', additionalProperties: true } } }), '401': response('Unauthorized', error) } } },
  },
  components: { securitySchemes: { adminBearer: { type: 'http', scheme: 'bearer', bearerFormat: 'opaque', description: 'Private admin token. Never paste a production token into an untrusted browser.' } } },
};

const site = (content: string, title: string) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Veyntis API</title><meta name="robots" content="noindex"><style>
:root{color-scheme:dark}body{margin:0;background:#091218;color:#eaf5ef;font:15px/1.7 system-ui,-apple-system,sans-serif}a{color:#8ee8bc}main{max-width:960px;margin:0 auto;padding:48px 24px}h1{font-size:clamp(32px,6vw,64px);letter-spacing:-.05em;line-height:1.1}h2{font-size:20px}.eyebrow{font:12px monospace;letter-spacing:.2em;color:#83deb4}.hero{border-bottom:1px solid #30463b;padding-bottom:35px}p{color:#aec5b9}.links{display:flex;gap:12px;flex-wrap:wrap;margin:30px 0}.links a{border:1px solid #507461;padding:10px 15px;border-radius:7px;text-decoration:none}.links a:first-child{background:#83deb4;color:#10231c;font-weight:700}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.card{padding:18px;border:1px solid #29453a;border-radius:9px;background:#11221e}code{font-family:ui-monospace,monospace;color:#97e2bd}.tag{font:11px monospace;color:#8ad9b0}footer{margin-top:55px;padding-top:15px;border-top:1px solid #30463b;color:#8da99a}</style></head><body>${content}</body></html>`;

const home = site(`<main><section class="hero"><div class="eyebrow">VEYNTIS / ENGINEERING INTERFACE</div><h1>Intelligence,<br>engineered into your operations.</h1><p>The Veyntis API supports business discovery, AI-assisted opportunity briefs, enquiry capture and controlled internal operations.</p><div class="links"><a href="/docs">Explore the API ↗</a><a href="/openapi.json">OpenAPI specification</a><a href="/api/health">Service health</a><a href="https://veyntis.vercel.app">Company website</a></div></section><h2>API capabilities</h2><div class="cards"><div class="card"><div class="tag">01 / DISCOVERY</div><h2>AI assistance</h2><p>Structured conversations and opportunity briefs for prospective clients.</p></div><div class="card"><div class="tag">02 / ENQUIRIES</div><h2>Lead intake</h2><p>Validated enquiries with persistent storage and optional notifications.</p></div><div class="card"><div class="tag">03 / INTERNAL</div><h2>Business operations</h2><p>Protected analytics, qualification and enquiry management.</p></div></div><footer>Veyntis · Nairobi, Kenya · API v1.0 · Documentation is public; admin operations require authentication.</footer></main>`, 'Overview');

const docsPage = site(`<main><div class="eyebrow">VEYNTIS / DEVELOPER DOCUMENTATION</div><h1>API Reference</h1><p>Public OpenAPI 3 specification and Swagger-style interactive API explorer. Protect secrets and avoid submitting real customer data when experimenting with endpoints.</p><div class="links"><a href="/openapi.json">View JSON specification</a><a href="/">API overview</a><a href="/api/health">Service health</a></div><p id="status">Loading the interactive API reference…</p><div id="swagger-ui"></div><noscript>Enable JavaScript to load Swagger UI, or read the <a href="/openapi.json">OpenAPI specification</a>.</noscript><footer>Admin endpoints require a private bearer token. The public documentation does not expose it.</footer></main><link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css"><style>#swagger-ui{background:#fff;color:#161e1b;border-radius:10px;overflow:hidden}#swagger-ui .topbar{display:none}#swagger-ui .scheme-container{box-shadow:none}</style><script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script><script>(function(){var s=document.getElementById('status');if(!window.SwaggerUIBundle){s.textContent='Interactive viewer unavailable (CDN blocked). The OpenAPI JSON above remains available.';return;}s.remove();SwaggerUIBundle({url:'/openapi.json',dom_id:'#swagger-ui',deepLinking:true,displayOperationId:false,docExpansion:'list',persistAuthorization:false,tryItOutEnabled:false});})();</script>`, 'API Reference');

export function registerApiDocumentation(app: FastifyInstance): void {
  app.get('/', async (_request, reply) => reply.type('text/html; charset=utf-8').send(home));
  app.get('/docs', async (_request, reply) => reply.type('text/html; charset=utf-8').send(docsPage));
  app.get('/docs/', async (_request, reply) => reply.redirect('/docs'));
  app.get('/openapi.json', async (_request, reply) => reply.send(openApiDocument));
}
