import { Logo } from '../components/Logo';
import { Contact } from '../sections/Contact';
import { Legal } from '../sections/Legal';
import { Chatbot } from '../components/Chatbot';
import { ShipmentCheck } from './ShipmentCheck';
import './logistics.css';

export default function Logistics() {
  return <div id="top"><header className="site-header"><div className="container nav-wrap"><Logo href="/" /><nav className="nav-links" aria-label="Logistics navigation"><a href="#shipment-check">Try the sample</a><a href="#logistics-engagement">How we work</a></nav><a className="header-cta" href="#contact">Discuss your workflow →</a></div></header>
    <main><section className="logistics-hero"><div className="container"><p className="eyebrow">AI INTEGRATION FOR LOGISTICS TEAMS</p><h1>Less re-keying.<br />Clearer shipment files.</h1><p>Connect practical AI capabilities to the software, documents, and workflows your team already uses. Start with one recurring task, prove its value, and expand from there.</p><div className="hero-actions"><a className="button button--primary" href="#shipment-check">Try Shipment File Check →</a><a className="button button--ghost" href="#contact">Discuss a workflow</a></div><p className="logistics-caption">Freight forwarding · Customs preparation · Warehousing · Distribution</p></div></section>
    <section className="container logistics-offer"><p className="eyebrow">ONE PRACTICAL STARTING POINT</p><h2>From a document pack to information your team can use.</h2><div className="logistics-cards"><article><span>01 / PREPARE</span><h3>Find the useful information</h3><p>Identify shipment references, parties, quantities, and weights from the documents your team receives.</p></article><article><span>02 / REVIEW</span><h3>Make exceptions visible</h3><p>Show missing fields and disagreements alongside their sources. Your operator decides what is correct.</p></article><article><span>03 / CONNECT</span><h3>Work with existing tools</h3><p>Start with an agreed export. Add an approved integration into your forwarding, warehouse, or business system once the workflow is proven.</p></article></div></section>
    <ShipmentCheck />
    <section id="logistics-engagement" className="container logistics-offer"><p className="eyebrow">HOW WE WORK</p><h2>A clear scope before a larger commitment.</h2><div className="logistics-cards"><article><h3>Start with a conversation</h3><p>A short introductory call to understand one workflow, the tools involved, and whether we can help. No confidential documents required.</p></article><article><h3>Assess one workflow</h3><p>A paid, fixed-scope assessment: workflow map, baseline, sample evaluation, integration options, and a go/no-go pilot recommendation. Fee agreed before work begins.</p></article><article><h3>Prove a focused pilot</h3><p>One team, one workflow, agreed success measures, and human review. Support hours, operating costs, and further changes are scoped separately.</p></article></div><p>Other workflows worth exploring include supplier invoice reconciliation, reviewed status replies, and quote preparation. We first check whether your existing software already provides a suitable capability.</p><p>Our engineering approach is informed by experience building civil aviation authority systems. Demonstrations use invented data and do not represent client deployments or endorsements.</p></section>
    <Contact /><Legal /></main><footer className="container logistics-footer"><a href="/">Explore Aivanta</a><span>Practical AI. Connected to your business.</span></footer><Chatbot /></div>;
}
